//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UILayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int Id { get; set; }
        public int StockId { get; set; }
        public int Count { get; set; }
        public decimal Amount { get; set; }
        public int Tax { get; set; }
        public decimal TotalAmount { get; set; }
        public int InvoiceId { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
