//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UILayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int FirmId { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime Date { get; set; }
        public int PaymentType { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual PaymentType PaymentType1 { get; set; }
    }
}
